import type {
  ContactInfo,
  MinistryPillar,
  NavLink,
  Program,
  SocialLink,
  VisionValue,
} from "./types";

/** Official foundation name. */
export const SITE_NAME = "Divine Gospel Delight Foundation";

/** Primary tagline used across marketing surfaces. */
export const SITE_TAGLINE = "Restoring Hope and Dignity to Every Life";

/** Default Open Graph image path (generated by app/opengraph-image.tsx). */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

/** Primary navigation links. */
export const NAV_LINKS: NavLink[] = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/gallery", label: "Gallery" },
  { href: "/donate", label: "Donate" },
  { href: "/contact", label: "Contact" },
];

/** Social media profile links. */
export const SOCIAL_LINKS: SocialLink[] = [
  {
    href: "https://facebook.com/dgdelightfound",
    label: "Facebook",
    platform: "facebook",
  },
  {
    href: "https://twitter.com/dgdelightfound",
    label: "Twitter",
    platform: "twitter",
  },
  {
    href: "https://instagram.com/dgdelightfound",
    label: "Instagram",
    platform: "instagram",
  },
  {
    href: "https://youtube.com/@dgdelightfound",
    label: "YouTube",
    platform: "youtube",
  },
];

/** Public contact details. */
export const CONTACT_INFO: ContactInfo = {
  email: "divinegospeldelight.ministry@gmail.com",
  phone: "08037310730\n08033705759",
  address: "Lagos, Nigeria",
};

/** Three core ministry pillars. */
export const PILLARS: MinistryPillar[] = [
  {
    id: "gospel",
    title: "Gospel Through Service",
    description:
      "Propagating the Gospel through practical service that restores hope, dignity, and spiritual enrichment in communities.",
    icon: "heart",
  },
  {
    id: "compassion",
    title: "Humanitarian Care",
    description:
      "Meeting the needs of widows, orphans, teenage children, retirees, and other less privileged people with compassion.",
    icon: "hands",
  },
  {
    id: "empowerment",
    title: "Family Empowerment",
    description:
      "Growing family enrichment, parenting support, and pathways that help people move from existing to fulfilling purpose.",
    icon: "users",
  },
];

/** Focused humanitarian programs shown on the homepage. */
export const PROGRAMS: Program[] = [
  {
    id: "healthcare",
    category: "Health",
    title: "Community Health Support",
    description:
      "Advancing people’s health through outreach and care that restores dignity to vulnerable families across Nigeria.",
    imageUrl:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop",
    href: "/about",
  },
  {
    id: "education",
    category: "Education",
    title: "Learning & Empowerment",
    description:
      "Supporting education and empowerment so individuals can move from surviving toward fulfilling life purpose.",
    imageUrl:
      "https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=800&h=600&fit=crop",
    href: "/about",
  },
  {
    id: "family",
    category: "Family",
    title: "Family Enrichment Programs",
    description:
      "Equipping parents and households with guidance for effective parenting and sustainable family life.",
    imageUrl:
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&h=600&fit=crop",
    href: "/about",
  },
];

/** Vision values shown beside the asymmetric portrait block. */
export const VISION_VALUES: VisionValue[] = [
  {
    id: "integrity",
    title: "Hope Restored",
    description:
      "Meeting real needs with humanitarian and empowerment support that restores dignity.",
    icon: "verified",
  },
  {
    id: "inclusive",
    title: "For Every Background",
    description:
      "A platform where individuals irrespective of their backgrounds can discover purpose.",
    icon: "inclusive",
  },
  {
    id: "lasting",
    title: "From Existing to Purpose",
    description:
      "Helping people transition from just existing to fulfilling life purpose.",
    icon: "growth",
  },
];

/** Trusted partners displayed on the homepage. */
export const PARTNERS = [
  "Community Care",
  "Nigeria Trust",
  "Faith & Family",
  "Africa Reach",
  "Hope Partners",
] as const;

/** Suggested donation amounts in Naira. */
export const DONATION_AMOUNTS = [1000, 5000, 10000, 25000, 50000] as const;

/** Preset amounts shown on the donate page form (plus Custom). */
export const DONATE_PRESET_AMOUNTS = [25000, 50000, 100000] as const;
