import type {
  ContactInfo,
  MinistryPillar,
  NavLink,
  Program,
  SocialLink,
  VisionValue,
} from "./types";

/** Official foundation name. */
export const SITE_NAME = "Divine Gospel Delight Foundation";

/** Primary tagline used across marketing surfaces. */
export const SITE_TAGLINE = "Humanitarian Impact in Nigeria";

/** Default Open Graph image path (generated by app/opengraph-image.tsx). */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

/** Primary navigation links. */
export const NAV_LINKS: NavLink[] = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/gallery", label: "Gallery" },
  { href: "/donate", label: "Donate" },
  { href: "/contact", label: "Contact" },
];

/** Social media profile links. */
export const SOCIAL_LINKS: SocialLink[] = [
  {
    href: "https://facebook.com/dgdelightfound",
    label: "Facebook",
    platform: "facebook",
  },
  {
    href: "https://twitter.com/dgdelightfound",
    label: "Twitter",
    platform: "twitter",
  },
  {
    href: "https://instagram.com/dgdelightfound",
    label: "Instagram",
    platform: "instagram",
  },
  {
    href: "https://youtube.com/@dgdelightfound",
    label: "YouTube",
    platform: "youtube",
  },
];

/** Public contact details. */
export const CONTACT_INFO: ContactInfo = {
  email: "info@dgdelightfound.org",
  phone: "+234 (0) 800 DELIGHT",
  address: "12 Corporate Way, Victoria Island, Lagos, Nigeria",
};

/** Three core ministry pillars. */
export const PILLARS: MinistryPillar[] = [
  {
    id: "gospel",
    title: "Gospel Outreach",
    description:
      "Proclaiming the good news through community crusades, discipleship, and church planting that brings lasting spiritual renewal.",
    icon: "heart",
  },
  {
    id: "compassion",
    title: "Compassion Ministry",
    description:
      "Meeting practical needs with food relief, medical outreaches, and care for widows, orphans, and vulnerable families.",
    icon: "hands",
  },
  {
    id: "empowerment",
    title: "Community Empowerment",
    description:
      "Equipping people with skills, education support, and livelihood programs that restore dignity and self-sufficiency.",
    icon: "users",
  },
];

/** Focused humanitarian programs shown on the homepage. */
export const PROGRAMS: Program[] = [
  {
    id: "healthcare",
    category: "Healthcare",
    title: "Mobile Clinics & Wellness Initiatives",
    description:
      "Providing life-saving medical care and preventive health education to remote rural communities across Nigeria.",
    imageUrl:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop",
    href: "/about",
  },
  {
    id: "education",
    category: "Education",
    title: "Scholarships & Skill Acquisition",
    description:
      "Investing in the next generation of leaders through structured educational grants and vocational training centers.",
    imageUrl:
      "https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=800&h=600&fit=crop",
    href: "/about",
  },
  {
    id: "sustainability",
    category: "Sustainability",
    title: "Food Security & Clean Water",
    description:
      "Building resilient systems through borehole installations and agricultural support for local farming collectives.",
    imageUrl:
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&h=600&fit=crop",
    href: "/about",
  },
];

/** Vision values shown beside the asymmetric portrait block. */
export const VISION_VALUES: VisionValue[] = [
  {
    id: "integrity",
    title: "Integrity First",
    description:
      "Transparent financial reporting and radical accountability in every naira spent.",
    icon: "verified",
  },
  {
    id: "inclusive",
    title: "Inclusive Grace",
    description:
      "Serving all people regardless of background, tribe, or religious affiliation.",
    icon: "inclusive",
  },
  {
    id: "lasting",
    title: "Lasting Change",
    description:
      "Moving beyond hand-outs to hand-ups through education and empowerment.",
    icon: "growth",
  },
];

/** Trusted partners displayed on the homepage. */
export const PARTNERS = [
  "Global Health",
  "Nigeria Trust",
  "Unity Bank",
  "Africa Reach",
  "Elite Charity",
] as const;

/** Suggested donation amounts in Naira. */
export const DONATION_AMOUNTS = [1000, 5000, 10000, 25000, 50000] as const;

/** Preset amounts shown on the donate page form (plus Custom). */
export const DONATE_PRESET_AMOUNTS = [25000, 50000, 100000] as const;
